# Generated by Django 5.0.14 on 2025-09-19 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('schemes', '0003_update_membersubscription_patient_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Billing Invoice', 'verbose_name_plural': 'Billing Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Billing Payment', 'verbose_name_plural': 'Billing Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Billing Payment Method', 'verbose_name_plural': 'Billing Payment Methods'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payment_methods', to='schemes.membersubscription'),
        ),
    ]
