# Generated by Django 5.2.5 on 2025-09-17 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_memberdocument_membermessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('PREAUTH_THRESHOLD', 'Pre-authorization Threshold'), ('DEFAULT_WAITING_PERIOD', 'Default Waiting Period (days)'), ('MAX_CLAIM_AMOUNT', 'Maximum Claim Amount'), ('AUTO_APPROVAL_ENABLED', 'Auto-approval Enabled'), ('FRAUD_DETECTION_ENABLED', 'Fraud Detection Enabled')], max_length=50, unique=True)),
                ('value', models.CharField(help_text='Setting value as string', max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
    ]
