# Generated by Django 5.0.14 on 2025-09-18 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_edivalidationrule_editransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the setting'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='key',
            field=models.CharField(help_text="Setting key (e.g., 'preauth_threshold')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='value',
            field=models.TextField(help_text='Setting value'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='value_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20),
        ),
    ]
