# Generated by Django 5.2.5 on 2025-08-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('INPATIENT', 'Inpatient'), ('IMAGING', 'Imaging')], max_length=50)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coverage_limit_count', models.PositiveIntegerField(blank=True, help_text='Max number of uses in period', null=True)),
                ('coverage_period', models.CharField(choices=[('PER_VISIT', 'Per Visit'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='schemes.schemecategory')),
            ],
            options={
                'unique_together': {('scheme', 'benefit_type')},
            },
        ),
    ]
