# Generated by Django 5.0.14 on 2025-09-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontier',
            options={'ordering': ['sort_order', 'monthly_price']},
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='benefit_categories',
            field=models.ManyToManyField(help_text='Benefit categories included in this tier', related_name='subscription_tiers', to='schemes.benefitcategory'),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='max_claims_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum claims per month', null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='max_coverage_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum coverage per year', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='tier_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='STANDARD', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontier',
            unique_together={('scheme', 'tier_type')},
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this tier includes'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this tier is currently available'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='max_dependents',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of dependents allowed'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='name',
            field=models.CharField(help_text='Tier name (e.g., Basic, Standard, Premium)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order for tiers'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, help_text='Yearly subscription price', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='updated_at',
        ),
    ]
