# Generated by Django 5.2.5 on 2025-08-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
    migrations.RunSQL("DELETE FROM schemes_schemebenefit;"),
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schemebenefit',
            name='benefit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_benefits', to='schemes.benefittype'),
        ),
    ]
