# Generated by Django 5.0.14 on 2025-09-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
        ('schemes', '0002_alter_subscriptiontier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='account_number_masked',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='card_number_masked',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='expiry_year',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='is_prorated',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='last_billing_date',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='outstanding_balance',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='membersubscription',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last_four',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='provider_payment_method_id',
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='claims_this_month',
            field=models.PositiveIntegerField(default=0, help_text='Number of claims this month'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='coverage_used_this_year',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coverage amount used this year', max_digits=12),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of last successful payment', null=True),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Date of next payment due', null=True),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscription', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number_masked',
            field=models.CharField(blank=True, help_text='Last 4 digits of account number', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_number_masked',
            field=models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='routing_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Whether subscription should auto-renew'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='end_date',
            field=models.DateField(help_text='Subscription end date'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='start_date',
            field=models.DateField(help_text='Subscription start date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_ACCOUNT', 'Bank Account'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='CREDIT_CARD', max_length=20),
        ),
    ]
