# Generated by Django 5.0.14 on 2025-09-19 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
        ('schemes', '0003_update_membersubscription_patient_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersubscription',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_subscription', to='claims.patient'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='claims.patient'),
        ),
    ]
