# Generated by Django 5.2.5 on 2025-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_add_price_to_schemecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemebenefit',
            name='copayment_fixed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount patient must pay per visit', max_digits=12),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='copayment_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of cost patient must pay', max_digits=5),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount patient pays before coverage kicks in', max_digits=12),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='network_only',
            field=models.BooleanField(default=False, help_text='Only cover in-network providers'),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='preauth_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount above which pre-auth is required', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='requires_preauth',
            field=models.BooleanField(default=False, help_text='Requires pre-authorization before treatment'),
        ),
        migrations.AddField(
            model_name='schemebenefit',
            name='waiting_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days to wait before benefit is active'),
        ),
        migrations.AlterField(
            model_name='schemebenefit',
            name='coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum coverage amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='schemebenefit',
            name='coverage_period',
            field=models.CharField(choices=[('PER_VISIT', 'Per Visit'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('LIFETIME', 'Lifetime'), ('BENEFIT_YEAR', 'Benefit Year')], default='BENEFIT_YEAR', max_length=20),
        ),
    ]
