# Generated by Django for scheme audit log

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0004_alter_membersubscription_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('DELETION_ATTEMPTED', 'Deletion Attempted'), ('DELETION_BLOCKED', 'Deletion Blocked')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=10)),
                ('scheme_id', models.IntegerField(help_text='Original scheme ID')),
                ('scheme_data', models.JSONField(help_text='Complete scheme data snapshot before action')),
                ('affected_members_count', models.PositiveIntegerField(default=0, help_text='Number of members affected by this action')),
                ('affected_benefits_count', models.PositiveIntegerField(default=0, help_text='Number of benefits affected by this action')),
                ('affected_subscriptions_count', models.PositiveIntegerField(default=0, help_text='Number of active subscriptions affected')),
                ('reason', models.TextField(blank=True, help_text='Reason provided for the action')),
                ('error_details', models.TextField(blank=True, help_text='Error details if action failed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, help_text='Time taken to complete the action', max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme Audit Log',
                'verbose_name_plural': 'Scheme Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='schemeauditlog',
            index=models.Index(fields=['scheme_id', 'action'], name='schemes_sch_scheme__1c6e62_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='schemes_sch_user_id_94b3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='schemes_sch_action_85f7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeauditlog',
            index=models.Index(fields=['status', 'timestamp'], name='schemes_sch_status_6b8e30_idx'),
        ),
    ]