# Generated by Django 5.2.5 on 2025-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_schemebenefit_copayment_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemebenefit',
            name='coverage_limit_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Max number of uses in period', null=True),
        ),
    ]
