# Generated by Django 5.2.5 on 2025-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_benefitcategory_subscriptiontier_membersubscription'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['scheme'], name='schemes_sch_scheme__bb2a18_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['benefit_type'], name='schemes_sch_benefit_65ad75_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['is_active'], name='schemes_sch_is_acti_f4d737_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['effective_date'], name='schemes_sch_effecti_fbdb10_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['expiry_date'], name='schemes_sch_expiry__f08bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['requires_preauth'], name='schemes_sch_require_e94d38_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['network_only'], name='schemes_sch_network_5fbd60_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['coverage_period'], name='schemes_sch_coverag_499738_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['scheme', 'is_active'], name='schemes_sch_scheme__e789c4_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['benefit_type', 'is_active'], name='schemes_sch_benefit_098318_idx'),
        ),
        migrations.AddIndex(
            model_name='schemebenefit',
            index=models.Index(fields=['scheme', 'benefit_type', 'is_active'], name='schemes_sch_scheme__c361a8_idx'),
        ),
    ]
