# Generated by Django 5.0.14 on 2025-10-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_add_scheme_soft_delete_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schemeauditlog',
            new_name='schemes_sch_scheme__f88f84_idx',
            old_name='schemes_sch_scheme__1c6e62_idx',
        ),
        migrations.RenameIndex(
            model_name='schemeauditlog',
            new_name='schemes_sch_user_id_b310e7_idx',
            old_name='schemes_sch_user_id_94b3e9_idx',
        ),
        migrations.RenameIndex(
            model_name='schemeauditlog',
            new_name='schemes_sch_action_0ded0b_idx',
            old_name='schemes_sch_action_85f7a7_idx',
        ),
        migrations.RenameIndex(
            model_name='schemeauditlog',
            new_name='schemes_sch_status_b3b8a9_idx',
            old_name='schemes_sch_status_6b8e30_idx',
        ),
        migrations.RenameIndex(
            model_name='schemecategory',
            new_name='schemes_sch_is_acti_ea4df4_idx',
            old_name='schemes_sch_is_acti_7f8a6e_idx',
        ),
        migrations.RenameIndex(
            model_name='schemecategory',
            new_name='schemes_sch_is_acti_79b6e5_idx',
            old_name='schemes_sch_is_acti_0b8e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='schemecategory',
            new_name='schemes_sch_deactiv_1282b4_idx',
            old_name='schemes_sch_deactiv_5f2a1c_idx',
        ),
    ]
