# Generated by Django 5.2.5 on 2025-08-09 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='service_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('INPATIENT', 'Inpatient'), ('IMAGING', 'Imaging')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient', 'service_type', 'status', 'date_submitted'], name='claims_clai_patient_1d1dd3_idx'),
        ),
    ]
