# Generated by Django 5.0.14 on 2025-09-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='schemes.benefittype'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='patient',
            name='principal_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='schemes.schemecategory'),
        ),
        migrations.AddField(
            model_name='patient',
            name='subscription',
            field=models.OneToOneField(blank=True, help_text="Patient's subscription tier", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_subscription', to='schemes.membersubscription'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='preauthorizationapproval',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauth_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preauth_requests', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_preauths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauth_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauth_requests', to='schemes.benefittype'),
        ),
        migrations.AddField(
            model_name='preauthorizationapproval',
            name='preauth_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_details', to='claims.preauthorizationrequest'),
        ),
        migrations.AddField(
            model_name='preauthorizationrule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauth_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='claims_pati_status_c1f03f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['relationship'], name='claims_pati_relatio_741696_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status', 'relationship'], name='claims_pati_status_08e87c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['scheme'], name='claims_pati_scheme__3461f1_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='claims_pati_user_id_f0d6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['principal_member'], name='claims_pati_princip_caaa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['member_id'], name='claims_pati_member__9a2579_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='claims_pati_gender_a70b07_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['enrollment_date'], name='claims_pati_enrollm_8c14d2_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['benefit_year_start'], name='claims_pati_benefit_c4be1e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['scheme', 'status'], name='claims_pati_scheme__5d591d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user', 'status'], name='claims_pati_user_id_f1d6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['alert_type', 'severity', 'status'], name='claims_frau_alert_t_091e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['claim', 'status'], name='claims_frau_claim_i_26f223_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['patient', 'created_at'], name='claims_frau_patient_1068aa_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['provider', 'created_at'], name='claims_frau_provide_cfe5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['fraud_score', 'status'], name='claims_frau_fraud_s_3a0302_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['priority'], name='claims_clai_priorit_1b601a_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'priority'], name='claims_clai_status_3ce1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['date_submitted'], name='claims_clai_date_su_fe3804_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['date_of_service'], name='claims_clai_date_of_243622_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['processed_date'], name='claims_clai_process_75c487_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient'], name='claims_clai_patient_d7ddbd_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['provider'], name='claims_clai_provide_dc1a53_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['service_type'], name='claims_clai_service_92109f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['processed_by'], name='claims_clai_process_5c3041_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient', 'status'], name='claims_clai_patient_02bd13_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient', 'date_submitted'], name='claims_clai_patient_57602d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['provider', 'status'], name='claims_clai_provide_abf6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['service_type', 'status'], name='claims_clai_service_1ec9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'date_submitted'], name='claims_clai_status_7df35a_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['coverage_checked'], name='claims_clai_coverag_e2bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['coverage_checked', 'status'], name='claims_clai_coverag_34bf82_idx'),
        ),
        migrations.AddIndex(
            model_name='preauthorizationrequest',
            index=models.Index(fields=['patient', 'status', 'date_requested'], name='claims_prea_patient_e7917d_idx'),
        ),
        migrations.AddIndex(
            model_name='preauthorizationrequest',
            index=models.Index(fields=['provider', 'status', 'date_requested'], name='claims_prea_provide_42c16c_idx'),
        ),
        migrations.AddIndex(
            model_name='preauthorizationrequest',
            index=models.Index(fields=['request_number'], name='claims_prea_request_3e1877_idx'),
        ),
        migrations.AddIndex(
            model_name='preauthorizationrequest',
            index=models.Index(fields=['status', 'priority', 'date_requested'], name='claims_prea_status_1f822b_idx'),
        ),
    ]
