# Generated by Django 5.0.14 on 2025-09-19 00:32

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Emergency contact name (encrypted)', max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Emergency contact phone (encrypted)', max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Patient phone number (encrypted)', max_length=150),
        ),
    ]
