# Generated by Django 5.2.5 on 2025-08-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_service_type_and_more'),
        ('schemes', '0002_benefittype_alter_schemebenefit_benefit_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='claim',
            new_name='claims_clai_patient_14fad6_idx',
            old_name='claims_clai_patient_1d1dd3_idx',
        ),
        migrations.RunSQL(
            sql=(
                """
                -- Ensure required benefit types exist
                INSERT INTO schemes_benefittype (name) VALUES ('CONSULTATION') ON CONFLICT (name) DO NOTHING;
                INSERT INTO schemes_benefittype (name) VALUES ('LAB') ON CONFLICT (name) DO NOTHING;
                INSERT INTO schemes_benefittype (name) VALUES ('PHARMACY') ON CONFLICT (name) DO NOTHING;
                INSERT INTO schemes_benefittype (name) VALUES ('IMAGING') ON CONFLICT (name) DO NOTHING;
                -- Map textual service_type values to the corresponding BenefitType IDs (as text)
                UPDATE claims_claim AS c
                SET service_type = bt.id::text
                FROM schemes_benefittype AS bt
                WHERE c.service_type = bt.name;
                """
            ),
            reverse_sql=(
                """
                -- Attempt to map IDs back to names if needed (best effort)
                UPDATE claims_claim AS c
                SET service_type = bt.name
                FROM schemes_benefittype AS bt
                WHERE c.service_type::bigint = bt.id;
                """
            ),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='schemes.benefittype'),
        ),
    ]
