# Generated by Django 5.0.14 on 2025-09-19 00:33

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_increase_encrypted_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='diagnosis_code',
            field=core.encryption.EncryptedCharField(blank=True, help_text='ICD-10 or other diagnosis code (encrypted)', max_length=150),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedure_code',
            field=core.encryption.EncryptedCharField(blank=True, help_text='CPT or other procedure code (encrypted)', max_length=150),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_bank_account',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Provider bank account number (encrypted)', max_length=150),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_bank_name',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Provider bank name (encrypted)', max_length=150),
        ),
    ]
