# Generated by Django 5.2.5 on 2025-08-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_add_member_id_to_patient'),
        ('claims', '0003_rename_claims_clai_patient_1d1dd3_idx_claims_clai_patient_14fad6_idx_and_more'),
    ]

    operations = [
    ]
