# Generated by Django 5.2.5 on 2025-08-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_merge_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
