# Generated by Django 5.0.14 on 2025-09-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_increase_all_encrypted_field_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='subscription',
        ),
    ]
