# Generated by Django 5.2.5 on 2025-08-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_add_patient_status'),
        ('schemes', '0004_schemebenefit_copayment_fixed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('authorization_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('diagnosis_code', models.CharField(help_text='ICD-10 or other diagnosis code', max_length=20)),
                ('procedure_code', models.CharField(help_text='CPT or other procedure code', max_length=20)),
                ('clinical_notes', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='date_of_service',
            field=models.DateField(blank=True, help_text='Date when the service was provided', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='diagnosis_code',
            field=models.CharField(blank=True, help_text='ICD-10 or other diagnosis code', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='preauth_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='preauth_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='procedure_code',
            field=models.CharField(blank=True, help_text='CPT or other procedure code', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient_coinsurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient_copay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient_deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='benefit_year_start',
            field=models.DateField(blank=True, help_text='Custom benefit year start (if different from enrollment)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Date of enrollment in the scheme', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='principal_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal Member'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('DEPENDENT', 'Other Dependent')], default='PRINCIPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUIRES_PREAUTH', 'Requires Pre-authorization'), ('INVESTIGATING', 'Under Investigation')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount approved for payment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['provider', 'status', 'date_submitted'], name='claims_clai_provide_bc3295_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['date_of_service', 'status'], name='claims_clai_date_of_4caa6f_idx'),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preauthorizations', to='claims.patient'),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_preauths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_preauths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorization',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauthorizations', to='schemes.benefittype'),
        ),
    ]
