# Generated by Django 5.2.5 on 2025-09-17 12:53

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_preauthorization_claim_date_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='diagnosis_code',
            field=core.encryption.EncryptedCharField(blank=True, help_text='ICD-10 or other diagnosis code (encrypted)', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='notes',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Clinical notes (encrypted PHI)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedure_code',
            field=core.encryption.EncryptedCharField(blank=True, help_text='CPT or other procedure code (encrypted)', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='rejection_reason',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Rejection reason (may contain PHI)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_bank_account',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Provider bank account number (encrypted)', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_bank_name',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Provider bank name (encrypted)', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=core.encryption.EncryptedDateField(help_text="Patient's date of birth (encrypted for privacy)"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnoses',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Patient diagnoses (encrypted PHI)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Emergency contact name (encrypted)', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Emergency contact phone (encrypted)', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='investigations',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Medical investigations (encrypted PHI)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Patient phone number (encrypted)', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatments',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Medical treatments (encrypted PHI)'),
        ),
    ]
