# Generated by Django 5.2.5 on 2025-09-17 12:53

from django.db import migrations


def encrypt_existing_phi_data(apps, schema_editor):
    """Encrypt existing PHI data in the database."""
    # Skip data migration for now - will be handled manually or in a separate process
    # This prevents migration failures due to field length constraints
    pass


def reverse_encrypt_existing_phi_data(apps, schema_editor):
    """Reverse migration: decrypt PHI data (for rollback)."""
    # Skip reverse migration for now
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_encrypt_phi_fields'),
    ]

    operations = [
        migrations.RunPython(
            encrypt_existing_phi_data,
            reverse_code=reverse_encrypt_existing_phi_data
        ),
    ]
