# Generated by Django 5.2.5 on 2025-09-17 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_preauthorizationapproval_preauthorizationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DUPLICATE_CLAIM', 'Duplicate Claim'), ('UNUSUAL_FREQUENCY', 'Unusual Frequency'), ('AMOUNT_ANOMALY', 'Amount Anomaly'), ('PROVIDER_PATTERN', 'Provider Pattern'), ('PATIENT_PATTERN', 'Patient Pattern'), ('SERVICE_MISMATCH', 'Service Mismatch'), ('TEMPORAL_ANOMALY', 'Temporal Anomaly'), ('NETWORK_VIOLATION', 'Network Violation')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ESCALATED', 'Escalated')], default='ACTIVE', max_length=10)),
                ('title', models.CharField(help_text='Brief description of the alert', max_length=200)),
                ('description', models.TextField(help_text='Detailed explanation of the fraud pattern detected')),
                ('fraud_score', models.DecimalField(decimal_places=3, help_text='Calculated fraud risk score (0.000-1.000)', max_digits=5)),
                ('detection_rule', models.CharField(help_text='Name of the rule that triggered this alert', max_length=100)),
                ('detection_data', models.JSONField(default=dict, help_text='Additional data from the detection algorithm')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review process')),
                ('resolution_action', models.CharField(blank=True, help_text='Action taken to resolve the alert', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='claims.claim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='claims.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity', 'status'], name='claims_frau_alert_t_091e0e_idx'), models.Index(fields=['claim', 'status'], name='claims_frau_claim_i_26f223_idx'), models.Index(fields=['patient', 'created_at'], name='claims_frau_patient_1068aa_idx'), models.Index(fields=['provider', 'created_at'], name='claims_frau_provide_cfe5a8_idx'), models.Index(fields=['fraud_score', 'status'], name='claims_frau_fraud_s_3a0302_idx')],
            },
        ),
    ]
