# Generated by Django 5.2.5 on 2025-09-17 16:54

import core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_fraudalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=core.encryption.EncryptedTextField(blank=True, help_text='Reason for claim rejection (encrypted)'),
        ),
    ]
