# Generated by Django 5.2.5 on 2025-09-18 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claim_rejection_date_claim_rejection_reason'),
        ('schemes', '0007_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['priority'], name='claims_clai_priorit_1b601a_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'priority'], name='claims_clai_status_3ce1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['date_submitted'], name='claims_clai_date_su_fe3804_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['date_of_service'], name='claims_clai_date_of_243622_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['processed_date'], name='claims_clai_process_75c487_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient'], name='claims_clai_patient_d7ddbd_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['provider'], name='claims_clai_provide_dc1a53_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['service_type'], name='claims_clai_service_92109f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['processed_by'], name='claims_clai_process_5c3041_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient', 'status'], name='claims_clai_patient_02bd13_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient', 'date_submitted'], name='claims_clai_patient_57602d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['provider', 'status'], name='claims_clai_provide_abf6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['service_type', 'status'], name='claims_clai_service_1ec9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'date_submitted'], name='claims_clai_status_7df35a_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['coverage_checked'], name='claims_clai_coverag_e2bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['coverage_checked', 'status'], name='claims_clai_coverag_34bf82_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='claims_pati_status_c1f03f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['relationship'], name='claims_pati_relatio_741696_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status', 'relationship'], name='claims_pati_status_08e87c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['scheme'], name='claims_pati_scheme__3461f1_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='claims_pati_user_id_f0d6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['principal_member'], name='claims_pati_princip_caaa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['member_id'], name='claims_pati_member__9a2579_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='claims_pati_gender_a70b07_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['enrollment_date'], name='claims_pati_enrollm_8c14d2_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['benefit_year_start'], name='claims_pati_benefit_c4be1e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['scheme', 'status'], name='claims_pati_scheme__5d591d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user', 'status'], name='claims_pati_user_id_f1d6ee_idx'),
        ),
    ]
