# Generated by Django 5.0.14 on 2025-09-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schemes', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providernetworkmembership',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to='schemes.schemecategory'),
        ),
        migrations.AddField(
            model_name='credentialingdocument',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.providernetworkmembership'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='credentialingreview',
            index=models.Index(fields=['status', 'priority', 'due_date'], name='accounts_cr_status_358ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialingreview',
            index=models.Index(fields=['reviewer', 'status'], name='accounts_cr_reviewe_44c706_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialingrule',
            index=models.Index(fields=['rule_type', 'doc_type', 'is_active'], name='accounts_cr_rule_ty_15b247_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexpiryalert',
            index=models.Index(fields=['alert_type', 'is_acknowledged', 'created_at'], name='accounts_do_alert_t_0f9be7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status', 'created_at'], name='accounts_no_recipie_b9b197_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'status'], name='accounts_no_notific_e98fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for', 'status'], name='accounts_no_schedul_8f4928_idx'),
        ),
        migrations.AddIndex(
            model_name='providernetworkmembership',
            index=models.Index(fields=['scheme', 'status'], name='accounts_pr_scheme__b20826_idx'),
        ),
        migrations.AddIndex(
            model_name='providernetworkmembership',
            index=models.Index(fields=['provider', 'status'], name='accounts_pr_provide_b01a10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providernetworkmembership',
            unique_together={('provider', 'scheme')},
        ),
        migrations.AddIndex(
            model_name='credentialingdocument',
            index=models.Index(fields=['membership', 'created_at'], name='accounts_cr_members_5dace2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'status'], name='accounts_us_user_id_37ae0c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_3fa67a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx'),
        ),
    ]
