# Generated by Django 5.2.5 on 2025-09-17 12:53

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_providerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Facility phone number (encrypted)', max_length=200),
        ),
    ]
