# Generated by Django 5.0.14 on 2025-09-19 00:25

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Facility phone number (encrypted)', max_length=150),
        ),
    ]
