# Generated by Django 5.0.14 on 2025-10-08 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_increase_phone_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent_color', models.CharField(default='#2E7DFF', max_length=16)),
                ('logo_url', models.CharField(blank=True, default='', max_length=255)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('timezone', models.CharField(default='UTC', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
