# Generated by Django 5.0.14 on 2025-10-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='member_messages_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='subscription_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLAIM_STATUS_UPDATE', 'Claim Status Update'), ('CREDENTIALING_UPDATE', 'Credentialing Update'), ('DOCUMENT_REVIEWED', 'Document Reviewed'), ('MEMBERSHIP_EXPIRING', 'Membership Expiring'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('GENERAL_ANNOUNCEMENT', 'General Announcement'), ('WELCOME_MEMBER', 'Welcome New Member'), ('SUBSCRIPTION_RENEWAL_REMINDER', 'Subscription Renewal Reminder'), ('MEMBER_MESSAGE', 'Message to Member')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('CLAIM_STATUS_UPDATE', 'Claim Status Update'), ('CREDENTIALING_UPDATE', 'Credentialing Update'), ('DOCUMENT_REVIEWED', 'Document Reviewed'), ('MEMBERSHIP_EXPIRING', 'Membership Expiring'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('GENERAL_ANNOUNCEMENT', 'General Announcement'), ('WELCOME_MEMBER', 'Welcome New Member'), ('SUBSCRIPTION_RENEWAL_REMINDER', 'Subscription Renewal Reminder'), ('MEMBER_MESSAGE', 'Message to Member')], max_length=30),
        ),
    ]
