# Generated by Django 5.2.5 on 2025-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_encrypt_existing_provider_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Encrypted backup codes for MFA recovery'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Whether MFA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False, help_text='Whether MFA is required for this user role'),
        ),
    ]
