# Generated by Django 5.2.5 on 2025-09-17 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_mfa_fields'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=5, help_text='Maximum concurrent sessions per user')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Session timeout in minutes')),
                ('block_suspicious_ips', models.BooleanField(default=True, help_text='Block sessions from suspicious IP addresses')),
                ('require_mfa_for_new_sessions', models.BooleanField(default=True, help_text='Require MFA verification for new sessions')),
                ('enable_session_monitoring', models.BooleanField(default=True, help_text='Enable detailed session monitoring')),
                ('alert_on_suspicious_activity', models.BooleanField(default=True, help_text='Send alerts for suspicious session activity')),
            ],
            options={
                'verbose_name': 'Session Settings',
                'verbose_name_plural': 'Session Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('location_info', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('SUSPICIOUS', 'Suspicious Activity')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('failed_mfa_attempts', models.PositiveIntegerField(default=0)),
                ('suspicious_activities', models.JSONField(blank=True, default=list)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_us_user_id_37ae0c_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_3fa67a_idx'), models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx')],
            },
        ),
    ]
