# Generated by Django 5.2.5 on 2025-09-17 13:04

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_session_models'),
    ]

    operations = [
        # Increase phone field length to accommodate encrypted data
        migrations.AlterField(
            model_name='providerprofile',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Facility phone number (encrypted)', max_length=200),
        ),
    ]
