# Generated by Django 5.2.5 on 2025-09-17 16:44

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_providerprofile_phone'),
        ('schemes', '0005_update_limit_count_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderNetworkMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('credential_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('credentialed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_memberships', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to='schemes.schemecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.provider_doc_path)),
                ('doc_type', models.CharField(choices=[('LICENSE', 'License'), ('CONTRACT', 'Contract'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentialing_uploads', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.providernetworkmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providernetworkmembership',
            index=models.Index(fields=['scheme', 'status'], name='accounts_pr_scheme__b20826_idx'),
        ),
        migrations.AddIndex(
            model_name='providernetworkmembership',
            index=models.Index(fields=['provider', 'status'], name='accounts_pr_provide_b01a10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providernetworkmembership',
            unique_together={('provider', 'scheme')},
        ),
        migrations.AddIndex(
            model_name='credentialingdocument',
            index=models.Index(fields=['membership', 'created_at'], name='accounts_cr_members_5dace2_idx'),
        ),
    ]
